version: "3"
services:
  postgres:
    build: postgres/
    container_name: postgres
    expose:
      - 5432
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=admin
      - POSTGRES_USER=postgres
      - POSTGRES_DB=engcompjr
    restart: unless-stopped
  app:
    build: .
    container_name: app
    expose:
      - 8080
    ports:
      - "8080:8080"
    restart: unless-stopped
    depends_on:
      - postgres
    links:
      - postgres